spring:
  profiles:
    include:
    - aws
    - elasticsearch
    - jwt

elasticsearch:
  index:
    course:
      name: course
    user:
      name: user
    post:
      name: post

cloud:
  aws:
    region:
      auto: false
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instance-profile: false
    s3:
      bucket: 
        user_profile: farmfather-user-profile
        course_thumbnail: farmfather-course-thumbnail
